services:
  minio:
    image: minio/minio:latest
    container_name: minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  init-minio:
    image: minio/mc:latest
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      until mc alias set local http://minio:9000 minio minio123; do sleep 2; done;
      mc mb -p local/cifar-remote || true;
      mc mb -p local/mlflow || true;
      mc mb -p local/zenml-artifacts || true;
      "

  mlflow:
    build:
      context: ./docker
      dockerfile: Dockerfile.mlflow
    container_name: mlflow
    depends_on:
      - minio
      - init-minio
    environment:
      AWS_ACCESS_KEY_ID: minio
      AWS_SECRET_ACCESS_KEY: minio123
      MLFLOW_S3_ENDPOINT_URL: http://minio:9000
      MLFLOW_SERVER_ALLOWED_HOSTS: "*"
    ports:
      - "5000:5000"
    volumes:
      - mlflow_data:/mlflow

  training:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    depends_on:
      - mlflow
      - minio
    environment:
      MLFLOW_TRACKING_URI: http://mlflow:5000
      MLFLOW_S3_ENDPOINT_URL: http://minio:9000
      AWS_ACCESS_KEY_ID: minio
      AWS_SECRET_ACCESS_KEY: minio123
      EPOCHS: "3"
      BATCH_SIZE: "128"
      NUM_WORKERS: "0"
      MAX_TRAIN_SAMPLES: "12000"
      MAX_VAL_SAMPLES: "2000"
    volumes:
      - .:/app

  monitoring:
    build:
      context: .
      dockerfile: docker/Dockerfile.monitor
    working_dir: /app
    depends_on:
      - mlflow
      - minio
    environment:
      MLFLOW_TRACKING_URI: http://mlflow:5000
      RETRAIN_ON_DRIFT: "false"
    volumes:
      - .:/app

  zenml:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zenml_dashboard
    working_dir: /app
    depends_on:
      - mlflow
      - minio
    command: sh -lc "zenml init --path /app && zenml up --blocking --ip-address 0.0.0.0 --port 8237"
    ports:
      - "8237:8237"
    volumes:
      - .:/app

volumes:
  minio_data:
  mlflow_data:
